#pragma once

#include "lvgl.h"

/* Auto-generated by main/modules/ui/font/buildFont */
extern const lv_font_t font_menu_icon;
#define FONT_MENU_ICON (&font_menu_icon)
#define ICON_MENU_DUIJIANG "\uEA00"
#define ICON_MENU_GUANYU "\uEA01"
#define ICON_MENU_LIANXI "\uEA02"
#define ICON_MENU_SHEZHI "\uEA03"
#define ICON_MENU_SHOUYE "\uEA04"
