#pragma once

/* Auto-generated by main/modules/ui/font/buildFont */
#define ICON_LINK "\uE9CB"
#define ICON_WIFI_1 "\uE900"
#define ICON_WIFI_2 "\uE901"
#define ICON_WIFI_3 "\uE902"
#define ICON_WIFI_FULL "\uE903"
#define ICON_WIFI_NO "\uE905"
