#pragma once

/* Auto-generated by main/modules/ui/font/buildFont */
#define ICON_LINK_WS_BREAK "\uE906"
#define ICON_LINK_WS_DONE "\uE907"
#define ICON_MENU "\uE900"
#define ICON_SETTINGS "\uE901"
#define ICON_WIFI_1 "\uE902"
#define ICON_WIFI_2 "\uE903"
#define ICON_WIFI_3 "\uE904"
#define ICON_WIFI_FULL "\uE905"
#define ICON_WIFI_NO "\uE908"
