#pragma once

/* Generated by ./fw. Keep VERSION as the source version number. */
#define APP_VERSION "0.2.0"
#define APP_GIT_TAG "v0.2.0"
#define APP_GIT_COMMIT "87f3b59"
#define APP_GIT_DIRTY 0
#define APP_FIRMWARE_VERSION "v0.2.0-g87f3b59"
