#pragma once

/* ============================================================
 * 麦克风 / 对讲音频可调参数
 * ============================================================ */

/* 麦克风采集参数 */
#define MIC_SAMPLE_RATE 8000
#define MIC_BITS_PER_SAMPLE 32
/* 约定值：1=Mono, 2=Stereo */
#define MIC_CHANNEL_FORMAT 1

/* 麦克风 I2S DMA：提高可降低采集欠载概率，但增加 RAM 占用。 */
#define MIC_I2S_DMA_DESC_NUM 4
#define MIC_I2S_DMA_FRAME_NUM 160

/* 对讲音频采样：8kHz / 20ms 一帧。 */
#define INTERCOM_AUDIO_SAMPLE_RATE 8000
#define INTERCOM_AUDIO_FRAME_MS 20
#define INTERCOM_AUDIO_FRAME_SAMPLES ((INTERCOM_AUDIO_SAMPLE_RATE * INTERCOM_AUDIO_FRAME_MS) / 1000)

/* 对讲编码：0=PCM16，1=G.711 u-law。远程 WSS 默认用 u-law 降低码率。 */
#define INTERCOM_AUDIO_CODEC_PCM16 0
#define INTERCOM_AUDIO_CODEC_G711_ULAW 1
#define INTERCOM_AUDIO_CODEC INTERCOM_AUDIO_CODEC_G711_ULAW

#if INTERCOM_AUDIO_CODEC == INTERCOM_AUDIO_CODEC_G711_ULAW
#define INTERCOM_AUDIO_ENCODED_BYTES_PER_SAMPLE 1
#else
#define INTERCOM_AUDIO_ENCODED_BYTES_PER_SAMPLE 2
#endif

#define INTERCOM_AUDIO_FRAME_BYTES (INTERCOM_AUDIO_FRAME_SAMPLES * INTERCOM_AUDIO_ENCODED_BYTES_PER_SAMPLE)
#define INTERCOM_AUDIO_PCM16_FRAME_BYTES (INTERCOM_AUDIO_FRAME_SAMPLES * 2)

/* WebSocket 音频批量发送帧数。5 帧约 100ms，适合远程 WSS 降低写入频率。 */
#define INTERCOM_AUDIO_WS_BATCH_FRAMES 5

/* 麦克风后处理参数 */
#define MIC_NOISE_GATE_LOW_MEAN_ABS 40U
#define MIC_NOISE_GATE_MID_MEAN_ABS 100U
#define MIC_NOISE_GATE_HIGH_MEAN_ABS 180U
#define MIC_NOISE_GATE_LOW_GAIN_Q15 12288
#define MIC_NOISE_GATE_MID_GAIN_Q15 20480
#define MIC_NOISE_GATE_HIGH_GAIN_Q15 28672
#define MIC_NOISE_GATE_FULL_GAIN_Q15 32768
#define MIC_AUDIO_LIMIT 12000
